### ISSUE TITLE
Future release v1.0.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1008]
**Release  v1.0.0**

Target: Sept 25th 2023

Checks before merge:
- [x] Check repo size (remove branches with data files)
- [x] Decision on dependencies pyaml/tomli
- [x] Docs: Investigate links to Sphinx anchors/symbols in tabs not working (JL)
- [x] Determine if README docs badge should point to main

SH:
- [x] Add gpu_env_fallback option to platform. #1050
- [x] make sure executor works standalone
- [x] Optimize kill_cancelled_sims  #1043 / #1063
- [x] Support num_procs/num_gpus for generator  #1068
- [x] Support MPI_runner option in exe.submit (e.g., when using env_script) #1054
- [x] Allow oversubpscription num_procs (gen_specs["out"] option). #1058
- [x] Update forces examples
      - Make persistent forces the default for both simple and GPU (inc. update tutorials)
      - Update to OO interface
- [x] Document resource_sets, usg_gpus, num_procs, num_gpus in docs for gen specs   
- [x] Sort out the issue of links into tabs - esp. platform_specs:
      - Put platform_specs in a platform guide under resource manager (should do that anyway).
- [x] Add `final_gen_send` option that returns last sim results to gen. #1086

JL:
- [x] Move many/most examples to OO interface #1014 
- [x] Allow reuse of workflow&ensemble dir #1028 #1041
- [x] Remove workerID suffix from sim/gen output directories #1041
- [x] Separate ensemble.log and libE_stats.txt for diff workflows directories. #1027 #1041
- [x] Resolve PETSc/OpenMPI issue  #1064
- [x] Performance safe_mode default to False (with general debugging FAQ to put on (along with DEBUG logging) #1053 
- [x] Add output option for specifying no. of digits in libE output dirs (requested by Optimas) #1052 / #1066
- [x] Look at pinning dependencies for releases #1056 
- [x] Prevent mpi4py validation running during local comms (when using OO interface) #1065 
- [x] Additional docs refactors (including quickstart example) #992
- [x] Better handling of Ensemble.add_random_streams and ensemble.persis_info #1074 
- [x] Ensemble.out can be accessed as Ensemble.outputs #1075 
- [x] Obtain executor instance from libE_info (4th parameter) in user-functions #1078 

Changes to defaults:

- [x] safe_mode defaults to False
- [x] kill_canceled_sims defaults to False

External:

- [x] Update template for HPC tests
- [x] Optimas testing.

Not done / postponed
- [ ] #801
- [ ] Update to be compatible with Pydantic 1 and 2, if possible. (JLN Note: Probably not possible)
- [ ] Allow decorating/labeling user functions with input/output attributes #1011

**Comment by jlnav** [comment]
Presumably closed by #1095 !
