### ISSUE TITLE
Release v0.4.1

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#115]
Next release v0.4.1

- [x] Logging to no longer uses root logger #105 
- [x] Add wait_on_run option for job controller #111
- [x] persis_info can be passed to sim as well as gen functions #112
- [x] Post-processing scripts added to create performance/utilization graphs #102
- [x] New scaling test added (not part of current CI test suite) #114 
- [x] Fix travis build issues #113
- [x] Remove queue_update_function #78
