### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1153]
Target: Wed Nov 8th 2023

Minor release.

- [x] New history array save options  #1103 / #1139 / #1141
- [x] Formal support for Python 3.12
- [x] Drop support of Python 3.8

Internal
- [x] Coverage changed to codcov #1147
- [x] Unsed comms code removed #1123
- [x] Support for threaded comms (undocumented) #1156
