### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1198]
Target: Feb 2024

- [x] Decorators to provide user function in/out specs #1072
- [x] Add platform support for Aurora (inc. guide) / support for GPU tiles #1183
- [x] Add platform guide for Improv. #1235
- [x] Support for Pydantic 1 and 2 #1135
- [x] Add gpCAM generator #1189 / #1213 / #1220
- [x] Support object dtype in history array #1179 / #1181
- [x] Bug fix - Overwrite history file on completion when even when the pathname is unchanged #1177 
- [x] Fix Sine tutorial #1168
- [x] Set ensemble.nworkers when parse_args is False #1162
- [x] Prevent duplicate save when using  save_every_k_gens #1154
- [x] Detection of Perlmutter GPU nodes updated #1211
- [x] Users can add additional fields to output arrays in user functions #1203  
- [x] Make `srun` GPU setting default to `gpus_per_task` instead of `gpus_per_node` #1206
- [x]  Add `mock_sim` to extract output from (replay) a previous run #1207 
- [x] Add a FAILED_TO_START task status #1229
- [x] Add mock sim that uses previous history file #1207 
- [x] Remove Theta support and guide #1200 
- [x] Interface APSOMM with IBCDFO optimizers #998

Internal
- [x] Adding sine and forces tutorial to CI 
- [x] Replaced coveralls in CI with codecov #1147 

API additions
- platform spec `tiles_per_gpu`
- libE_specs option `use_tiles_as_gpus`

**Comment by jlnav** [comment]
Closed by #1237
