### ISSUE TITLE
Release v1.2.2

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1234]
Target: March 22 2024

- [x]  `platform_specs` is merged with detected platform specs #1265 
- [x] Bugfix: Some libE_specs were not passed through after ensemble initialization. #1264
- [x]  Ensure simulations directories are created when sim_input_dir is specified, likewise for gen dirs #1266 

Use-cases:
- [x] Improved structure of gpCAM generator #1260

**Comment by jlnav** [comment]
Closed by recent release
