### ISSUE TITLE
Release v1.3.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1268]
Target: May 01 2024

Before release:
- [x] Check documentation. Is gen_on_manager and change to default comms documented sufficiently.
- [x] Polaris build (conda module disappeared - still in Polaris docs) - see if need to update Polaris instructions (tested using cray-python module) Now also tested with conda module - need first use: module use /soft/modulefiles

Features:

- [x] Support generator running on the manager on thread. #1216/#1290
- [x] Default to local comms when num_workers is supplied and no MPI runner detected .#1169
- [x] Parse args defaults to local comms when nworkers is set on command line (via --nworkers or -n). #1169

Possible:

- [ ] Improve coverage of core libE methods (if reasonably easy to do so). Files to consider
  - [ ] [libE.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2FlibE.py)
    - [x] `on_abort`, `on_cleanup` method
    - [ ] TCP worker-side content.
  - [ ] Should all of [worker.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fworker.py) be covered?
  - [ ] [comms.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fcomms%2Fcomms.py)
  - [x] [executor.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fexecutors%2Fexecutor.py)
  - [x] [mpi_runner.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fexecutors%2Fmpi_runner.py)
    - [x] including `_adjust_procs`
  - [ ] [mpi_resources.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fmpi_resources.py) exception handling
  - [ ] [genfunc init](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fgen_funcs%2F__init__.py) where I think much might be removable.
  - [ ] ~~[gpu_detect](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fgpu_detect.py) but not if that's difficult to test/mock.~~ Same for [tcp_mgr](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fcomms%2Ftcp_mgr.py)
  - [ ] Slots in [worker_resources.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fworker_resources.py)
  - [x] What should happen in the `cores_info is None` case in [node_resources](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fnode_resources.py)

**Comment by shuds13** [comment]
I think gpu_detect is probably better left to HPC testing. We could mock something to check the output is received correctly, but it seems more important to test that we are interacting with the GPU detection packages correctly, by doing it for real.

**Comment by shuds13** [comment]
Those lines in [genfunc init](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fgen_funcs%2F__init__.py) were set up for `rsopt`. I sort of thought we had a test for it, but maybe it was in the windows testing. @jlnav ?

**Comment by shuds13** [comment]
In node_resources, the  `if _complete_set(cores_info):` in  `get_sub_node_resources` is not set as this would mean GPUs environment variable were detected, which is not set in any of the CI. We could have a unit test that sets `SLURM_GPUS_ON_NODE` env variable, but I'm a little cautious about setting meaningful environment variables in unit tests.
