### ISSUE TITLE
Release  1.4.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1297]
Release 1.4.0

Remember before release:
- [x] Ensure MPICH lock to 4.2.1 is removed and working.
- [x] Test notebooks after pulling into main.

Target: July 22 2024
- [x] Updates to support numpy 2.0. #1332 
- [x] Add a live_data option for real-time data collection / plotting. #1310
- [x] Update example notebooks, and add Colab support. #1310
- [x] Add examples in docs - showing templating of input files and providing to executor (json / jinja). #1310
- [x] Improve class interface support for setting nworkers/is_manager when parse_args not used. #1331/ #1336 
      - This update locks the comms method when `Ensemble` object is created.
      - Ensure example in readme, notebooks, tests, and docs are in format we want given Ensemble() comms lock.
- [x] Add `group_size` option to deal with unevenly resourced nodes. #1349 
- [x] Bug fix: Fix shutdown hang on worker error when using `gen_on_manager`. #1348 
- [x] Bug fix: Log level was locked to "INFO" when using class interface. #1351
- [x] Resolve situation with one_d_func  #1352 / #1354
- [x] Update gpCAM gens to work with latest interface, and improve (simple/max_iter etc...). #1355
