### ISSUE TITLE
Future release (1.4.x or 1.5.0 or 2.0)

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1350]
Superceeded by #1681

Question: Should `gen_on_manager` becomes default (what about non-persistent gens). This is very breaking hence might be for 2.0.

- [ ] Support sub-classed generators with an ask/tell interface #1240 
- [ ] Make sure persistent gens return None as first parameter unless want to return something.
- [x] Resolve #1403 and #1404
- [ ] Updating forces and other examples (inc. notebooks) to use gen on manager. Update platform tutorials.
- [ ] Better interface support for generator running outside of libE (and make example notebook).
- [x] Create unified index of examples - based on gen type - points to location (libE or community examples) and shows gen/calling script examples.
- [ ]  In the Sim function examples add  links to community examples  (and/or WarpX/Opal when these are up to date).

- [ ] Improve coverage of core libE methods (if reasonably easy to do so). Files to consider
  - [ ] [libE.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2FlibE.py)
    - [ ] TCP worker-side content.
  - [ ] Should all of [worker.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fworker.py) be covered?
  - [ ] [comms.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fcomms%2Fcomms.py)
  - [ ] [mpi_resources.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fmpi_resources.py) exception handling
  - [ ] [genfunc init](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fgen_funcs%2F__init__.py) where I think much might be removable.
  - [ ] ~~[gpu_detect](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fgpu_detect.py) but not if that's difficult to test/mock.~~ Same for [tcp_mgr](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fcomms%2Ftcp_mgr.py)
  - [ ] Slots in [worker_resources.py](https://app.codecov.io/github/Libensemble/libensemble/blob/develop_coverage/libensemble%2Fresources%2Fworker_resources.py)

Canceled / Put on hold:
- [ ] Support generator running on the manager #1142 (in-place)
- [ ] Allow num workers to be set by detected GPUs #939
- [ ] Add notebook with simple optimization example - inc. simple persistent generator (similar to paper example).

Questions: 

- Should `use_persis_return_sim` be deprecated - if so now or next release. Requires ensuring all functions update to returning None (including in docs) - which should do anyway.
- Should H0 be an argument to ensemble.run()?
- naming "persistent_" do we update as most examples are persistent (2.0 consideration).
- Consider order of arguments to Ensemble object

**Comment by jlnav** [comment]
>  Make sure persistent gens return None as first parameter unless want to return something.

Out of curiosity, I think functions that return "nothing" already have their output parameter captured as None, e.g.

```
>>> out = print("HELLO")
>>> type(out)
<class 'NoneType'>
```

Within the worker, current logic, probably can be dramatically improved:

```
            if out:
                if len(out) >= 3:  # Out, persis_info, calc_status
                    calc_status = out[2]
                    return out
                elif len(out) == 2:  # Out, persis_info OR Out, calc_status
                    if isinstance(out[1], (int, str)):  # got Out, calc_status
                        calc_status = out[1]
                        return out[0], Work["persis_info"], calc_status
                    return *out, calc_status  # got Out, persis_info
                else:
                    return out, Work["persis_info"], calc_status
            else:
                return None, Work["persis_info"], calc_status
```

Looks like if a gen returns None or otherwise, the intention may be captured anyway? I dunno

**Comment by jlnav** [comment]
Fair enough; by the last set of points do you mean the last generated, but not sent out, set of points being added as duplicates? Would those points having sim_ids by that point prevent duplication? Maybe I'm missing something

**Comment by shuds13** [comment]
> Fair enough; by the last set of points do you mean the last generated, but not sent out, set of points being added as duplicates? Would those points having sim_ids by that point prevent duplication? Maybe I'm missing something

Look at this code, which is typical for our persistent gens.

```python

    while tag not in [STOP_TAG, PERSIS_STOP]:
        H_o = np.zeros(b, dtype=gen_specs["out"])
        H_o["x"] = persis_info["rand_stream"].uniform(lb, ub, (b, n))
        tag, Work, calc_in = ps.send_recv(H_o)


    return H_o, persis_info, FINISHED_PERSISTENT_GEN_TAG

```

H_o is sent to the manager in `ps.send_recv(H_o)`. Then at end those points are returned (again). They get added twice. We decided to ignore the return H_o unless `use_persis_return_gen` is set, in order to prevent that. Also, bear in mind, users will have used these as templates to their own gens.
