### ISSUE TITLE
Release 1.4.2

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1399]
Target date: ASAP

- [x] Fix under-utilized resource usage. #1398
 -  Fixes bug causing executor to wrongly increase processor counts when not all nodes are utilized.
 - Fixes case where setting `num_gpus` to zero was treated as `None`.
- [x] Add proxystore example. #1326 
- [x] Add missing PerlmutterGPU specs. #1393 
- [x] Handle case where Perlmutter detected but no partition. #1391 
- [x] Launch environment scripts in shell. #1392

**Comment by jlnav** [comment]
Done!
