### ISSUE TITLE
Release 1.4.3

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#1485]
Target date: Dec 13 2024

- [x] Fix wait_on_start type-instance condition checking #1474
- [x] Resolve pydantic warnings. #1410
- [x] Only show worker node in the log when running in a distributed mode and with DEBUG logging. #1486
- [x] Add `VDEBUG` logging level for the tracking of log message communications. #1486
- [x] Update uneven distribution messaging. #1486
- [x] Add APOSMM opt run plot scripts. #1461 
- [x]  Converted test runner to Python. #1437 

Cannot reproduce:
~~-[ ] Resolve DeprecationWarning: pkg_resources is deprecated as an API. #1444~~

**Comment by jlnav** [comment]
Closed by #1488 !
