### ISSUE TITLE
Release v0.5.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#171]
Next release v0.5.0

- [x] Dropping support for Python 2.
- [x] Create inheritable comms module adding local(multiprocessing) and tcp options #42
- [x] Fix up logging in develop branch #110 
- [x] Add aprun and jsrun options to MPI job controller. #139 
- [x] Make auto_resources work with multiprocessing #142 
- [x] Support LSF schedular (test of Summit) - also #142
- [x] Streamline regression tests, removing duplicate code #121 
- [x] Simple libE use cases should not require a gen_func #122 
- [x] Add basic capability to get job times in libE_stats.txt #136 
- [x] Extend forces test to test kills and variable workloads #138 
- [x] Add mechanism in job controller to re-try launches on failure #143 
- [x] Change default logging level to INFO #164
- [x] Fix intermittent hangs in test_calc_exception.py
- [x] Allow log filename to be provided. #109 

APOSMM:

- [x] Support scipy.minimize #117 
- [x] Remove use of global variables in APOSMM #118 

Known limitations:
- OpenMPI does not work with direct launches with mpi4py comms as it does not support nested MPI launches.
- Local comms mode (multiprocessing) may fail if MPI is initialized before forking processors. This is thought to be responsible for issues combining with PETSc.
- Remote detection of logical cores via LSB_HOSTS (e.g. Summit) returns number of physical cores as SMT info not available.
- TCP mode does not support the auto-resources option to the job controller.
