### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#193]
Next release v0.5.1

- [x] Fix LSF resource detection for large jobs on LSF systems (e.g. Summit) #184 
- [x] Create environment resources class #186 
- [x] Add beginner's tutorial to documentation #183
- [x] Update developer documentation #190 
- [x] Add FAQ to documentation #192 
- [x] Add release process to documentation #195 
- [x] Support libEnsemble testing on macOS #182

These will be added in the next release (v0.5.2) depending on timescale:
 - Changes for xSDK compatibility.
-  Add macOS testing to Travis
