### ISSUE TITLE
Release v0.5.2

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#226]
Next release v0.5.2

- [x] Achieve xSDK compliance (see 208 for sub-tasks) #208
- [x] Every worker copies/enters sim_dir even when they never do sim work #146 
- [x] Allow for a serial check_inputs for users #65 
- [x] Added macOS testing to Travis PR #206
- [x] Addition of profiling option PR #170
- [x] Allow users to install extended dependencies with pip install libensemble[extras]
- [x] Fix to job_controller_hworld test to prevent failures (forces batch generation) #50
- [x] Fix to timer test to prevent failures (does not depend on system overhead) #202
- [x] Introduce manager_warning log level and echo to standard error (with option to change echo level) 
- [x] Checking that sim_ids are given in order PR #213
