### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#284]
Next release v0.6.0

- [x] Add Balsam testing to Travis. #47 
- [x] Include multiprocessing runs in coverage. #245 
- [x] Consolidation of libE_specs #272
- [x] Constrain user defined sim/gen/alloc specs to user field. #266 and #269
- [x] Add OpenMP threading and GPU support to forces test #250
- [x] Auto-resource fix to support Cori #233 
- [x] Documentation: Add Platforms install guide inc. Bebop/Summit/Theta #232
- [x] Fix the NumPy FutureWarnings in unit test output #234
- [x] Re-arrange docs and pdf structure (also add new sections) #282 
- [x] Aposmm persistent implementation include #217
- [x]  Mention inclusion in xSDK
- [x] Added libEnsemble Utilities module  #308
- [x] Add more example submission scripts to cover main platforms

**Comment by jlnav** [comment]
I'm considering delaying updating balsam_controller with any new helper-functions until another Balsam release. This way we don't rewrite the controller based on features that may end up changing dramatically. Thoughts?

**Comment by shuds13** [comment]
Thats sounds fine. What about the part about no longer support keyword args - did you make a change for that? We could probably go back to explicit arg list?

**Comment by jmlarson1** [comment]
I think this is satisfied. See the definition of 
````allowed_sim_spec_keys, allowed_gen_spec_keys, allowed_alloc_spec_keys, allowed_libE_spec_keys```` and their usage in https://github.com/Libensemble/libensemble/blob/develop/libensemble/utils.py

Is that what you are thinking about?

**Comment by jmlarson1** [comment]
That was in PR #281

**Comment by shuds13** [comment]
I was thinking about #274 - this bit:

Balsam 0.3.7's add_job() in dag.py no longer supports custom keyword args. This causes libE's balsam_controller.py to fail when unexpected keyword args are encountered in job.process = dag.add_job(**add_job_args).

**Comment by jlnav** [comment]
It looks like they were nice enough to re-add custom keywork args: 

https://github.com/balsam-alcf/balsam/commit/b2539f21020b452bb43cacf476efadaafe9acc87

I'm exploring undoing my recent kwarg pull request with another.

**Comment by shuds13** [comment]
Release completed
