### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#403]
Next release v0.7.0
- [x] Renaming of Job_controller/Job to Executor/Task and launch to submit (API change) #285
- [x] Move Executors/Resources/Utils into sub-packages. (API change) #285
    (includes moving sim/gen/alloc support functions into utils/tools dir.)
- [x] Restructuring of sim/gen directory creation when input directories are provided. (API change) (add/change/output). #267
- [x] Provide alloc specs defaults via alloc_funcs.defaults #325 
- [x] More accurate timing in libE_stats. #318
- [x] Add libE_specs option to disable log files #368
- [x] Bugfix: Intermittent failures with repeated libE calls under mpi4py comms #373/#387
    (Every libE call uses its own duplicate of provided communicator and closes out.)
- [x] Add check that sim['in'] fields exist in some 'out' specs or H0 #382
- [x] Interface libEnsemble with a generator function that can identify finite difference parameters #350
- [x] Add example gen func: Tasmanian UQ generator.  #351
- [x] Add example sim func: Borehole #367
- [x] Add HPC testing repo with templater. #386

- [x] ~~Add forces/aposmm test to scaling tests #391~~ Fulfilled by warpx/aposmm test
- [x] Ensure worker exceptions and manager shutdown is part of scaling tests #390
- [x] Check all options listed in docs.
- [x] Add gen_funcs.rc configuration framework with option to select APOSMM Optimizer for import #444
- [x] Update and document fallback method for supplying node list to libEnsemble. PR  #455
- [x] Add extra_args option to executor submit to allow addition of arbitrary MPI runner options #445
- [x] Add WarpX test case for testing. PR  #425
- [x] Add conda-forge libEnsemble package and update release process and install guides.
- [x] Update sim/gens in documentation (and rc_aposmm_optimizer)
- [x] Check highlighting is correct in examples (e.g. calling scripts)
- [x] Add custom_info argument to MPI Executor to allow overriding of detected settings #448

**Comment by jmlarson1** [comment]
Are we close to this release?

**Comment by jlnav** [comment]
Assuming closed by #465
