### ISSUE TITLE
Release v.0.3.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#45]
Next release v0.3.0

Kill issues have been fixed (issue #21)
Testing improved
Exception handling improved.
...

To do:

- [x] Fix killing of user jobs #21 
- [x] Create history class #44 
- [x] Create manager class and refactor code #76 
- [x] Improve documentation #39
- [x] Need to dump history on exceptions #46 
- [x] Clean up job_controller (env/timing/job-return/comments)
- [x] Decide if mpi_abort should be the default???
- [x] Speed up job_controller unit tests #68
- [x] Dump history file on exceptions and mpi_abort #46 
- [x] Update Balsam code and launch script and run tests on Theta #75 
- [x] Modify manager_poll to work correctly for muliptle jobs #62 

-Make libE version of standalone kill test - no longer doing this for this release.

-Improve and test, or remove message error handling code in manager/worker. Not currently tested

**Comment by shuds13** [comment]
Version 0.3.0 released on September 7, 2018
