### ISSUE TITLE
Release v0.7.1

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#501]
Next release v0.7.1

- [x] Support zero resource workers for persistent gens #500 

- [x] Register applications by name. #498

- [x]  Add wait function to Tasks #499 

- [x] Add gen_dir capability #349 

- [x] Addition of psutils dependency #478 #491

- [x] Update HPC testing to include new features. (inc. Libensemble/libE-templater#27 Libensemble/libE-templater#29)

- [x]  APOSMM Tutorial #468

- [x] Create SciPy poster and Jupyter notebook of tutorials (host on Binder) #492 

- [x] Add posters and presentations section to docs #492 #497

- [x] Support for Python 3.8 on Linux #505 

- [x] Improve comms efficiency (Repack fields when numpy version 1.16+) #511

- [x] Add user function guide to docs. #510

- [x] Allow APOSMM to trigger ensemble exit when condition reached  #507

- [x] Improve how persistent APOSMM shut-downs subprocesses (e.g. prevents PETSc MPI-abort) (#478)

- [x] Fix multiprocessing error on macOS/Python3.8 (Use 'fork' instead of 'spawn') #502 / #503
