### ISSUE TITLE
Release v0.7.2

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#533]
Next release v0.7.2

- [x] In examples, `is_master` changed to `is_manager` to be consistent with manager/worker nomenclature. #524
- [x] Support for Python 3.9. #532
- [x] Add checks to `check_inputs`. #523
- [x] Fix crash when running on Windows. #534
- [x] Moved bulk of online CI to GitHub actions. See #563 / #577
- [x] Improved repack_fields use (reliability and efficiency). #543 / #544 / #557
- [x] Fixed crash when running with empty `persis_info`. #571 / #578
- [x] Miscellaneous internal module renames and refactorings. #576 #570
- [x] Make error handling more robust. #592
- [x] A mechanism is added for the cancellation/killing of previously issued evaluations. #528 / #595 / #596
- [x] A submit function is added in the base Executor class that runs a serial application locally. #531 / #595
- [x] Active receive option added that allows irregular manager/worker communication patterns. #527 / #595
- [x] Added Surmise calibration generator function and two examples (regression tests). #595 
- [x] Added tutorial _Borehole Calibration with Selective Simulation Cancellation_. #581 / #595
- [x] Add libE protected fields `returned_time`, `last_given_time`, `last_gen_time` #590
- [x] A global `sim_id` is now given, rather than a local count, in _libE_stats.txt_. Also a global gen count is given. #587, #588
- [x] If calc_status is None make it `UNSET_TAG`. #585
- [x] Removed usage of deprecated numpy types `np.float` and `np.int`. #584
- [x] Update versioning (note that develop now has _+dev_ suffix). #568
- [x] Removed 3.5 support. #562
- [x] Improve SLURM nodelist detection. #560
- [x] Update libE_specs options (`mpi_comm` and `profile`). #547 / #548
- [x] Add check that user does not change protected H fields (Disable via `libE_specs['safe_mode'] = False`). #541
- [x] Explicitly seeded random streams. #542 / #545
- [x] Improve `H0` processing. #536 / #537
- [x] Added print fields script. #558
- [x] Allow uneven worker to node distribution. #591 / #600
- [x] Update docs. #546 / #554 / #589

**Comment by jmlarson1** [comment]
Also, improved `github actions`. See #563 
Also, improved repack_fields use. See #557

**Comment by jlnav** [comment]
Fixed crash when running with empty ``persis_info`` #578
Miscellaneous internal module renames and refactorings #576 #570

**Comment by jmlarson1** [comment]
Can we do this release easily? I'd like to make some API changes on 0.8, but we should do this first.

**Comment by shuds13** [comment]
Once we've bought in surmise branch (target this week), and other (non-breaking) outstanding branches I think we should do it.

**Comment by shuds13** [comment]
@jmlarson1 @jlnav 

Proposed release notes:

:Date: April 30, 2021

API additions:
* Active receive option added that allows irregular manager/worker communication patterns. #527 / #595
* A mechanism is added for the cancellation/killing of previously issued evaluations. #528 / #595 / #596
* A submit function is added in the base ``Executor`` class that runs a serial application locally. #531 / #595
* Add libE protected fields `returned_time`, `last_given_time`, `last_gen_time` #590
* Update libE_specs options (``mpi_comm`` and ``profile``). #547 / #548
* Allow explicit seededig of random streams in ``add_unique_random_streams()`` #542 / #545


Updates to example functions:
* In examples, ``is_master`` changed to ``is_manager`` to be consistent with manager/worker nomenclature. #524

* Added Surmise calibration generator function and two examples (regression tests). #595


Other changes:
* Better support for uneven worker to node distribution (including at sub-node level). #591 / #600
* Fixed crash when running on Windows. #534
* Fixed crash when running with empty `persis_info`. #571 / #578
* Error handling is more robust. #592
* Improve ``H0`` processing (esp. for pre-generated, but not evaluated points) #536 / #537
* A global ``sim_id`` is now given, rather than a local count, in _libE_stats.txt_. Also a global gen count is given. #587, #588
* Added support for Python 3.9. #532 / Removed support for Python 3.5. #562
* Improve SLURM nodelist detection (more robust). #560
* Add check that user does not change protected history fields (Disable via ``libE_specs['safe_mode'] = False``). #541
* Added ``print_fields.py`` script for better interrogating the output history files. #558

Documentation:
* Added tutorial **Borehole Calibration with Selective Simulation Cancellation**. #581 / #595


:Note:

* Tested platforms include Linux, MacOS, Theta (Cray XC40/Cobalt), Summit (IBM Power9/LSF), Bebop (Cray CS400/Slurm).
* Tested Python versions: (Cpython) 3.6, 3.7, 3.8, 3.9.

:Known issues:

* OpenMPI does not work with direct MPI job launches in ``mpi4py`` comms mode, since it does not support nested MPI launches
  (Either use local mode or Balsam Executor).
* See known issues section in the documentation for more issues.


==========================================================================
Not included for lack of user relevance.

* Add checks to `check_inputs`. #523
* Moved bulk of online CI to GitHub actions. See #563 / #577
* Improved repack_fields use (reliability and efficiency). #543 / #544 / #557
* Miscellaneous internal module renames and refactorings. #576 #570
* If calc_status is None make it `UNSET_TAG`. #585
* Removed usage of deprecated numpy types `np.float` and `np.int`. #584
* Update versioning (note that develop now has _+dev_ suffix). #568
