### ISSUE TITLE
Release v0.8.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#663]
Next release v0.8.0

Work in progress, please add to this.

Questions...... 

@jlnav Is this one to be combined with new balsam - or will that be supported later?
- [ ] Balsam 0.4 support #605 / #616
- [ ] FBPIC - multi-fidelity example

@jmlarson1 Any more details for new tests? (for here / or release notes)
- [ ]  Suite of distributed optimization libraries for libEnsemble #647 

Also related to #624 we have discussed giving libE_info to allocs - needs discussion.
And making use_persis_return the default? See previous #613 / #618

------------------------

- [ ] Add Tasmanian dependency to Spack package spack/spack#25762
- [ ] Alternative libE parameterization interface #645

Breaking API changes:
- [ ]  Implement variable resource workers #643 
       - [ ] Separate resources from Executor  (Users can access worker resource attributes and functions) #345
- [ ] Minor name changes (API change)  #529 / #659
- [ ] Review gen_specs['in'] in light of persistent gens.. #626
- [ ] Make alloc support module a class #643 / #656
- [ ] Construct Class for Persistent Worker support functions #609
- [ ] Remove 'libE_' prefixes from core modules (includes logger which is user facing) #573 / #608
- [ ]  `avail_worker_ids` function should specifiy EVAL_GEN_TAG or EVAL_SIM_TAG instead of True #615

- [ ] Break main loop when sim_max is returned #624
- [ ] Implement helper function or executor option for generic task polling loop #572 / #612
- [ ] Enable final communication with gen. #620 / #628
- [ ]  Allowing to users to tell the manager to not check whether to cancel … #637 
- [ ]  Trying to grow_H in a more logical fashion #636 
- [ ]  Feature/iprobe and logging update #629 

- [ ] Split or categorize regression tests by if they require additional dependencies #611
- [ ] Adds filter label for "extra" regression tests #654
- [ ] Create a persistent sim example #614 / #615
- [ ] DeepDriveMD inspired workflow #630
- [ ] Added batched construction for Tasmanian example #644 
- [ ] An initial gen capabilities list #617

**Comment by jlnav** [comment]
> @jlnav Is this one to be combined with new balsam - or will that be supported later?

New Balsam is probably going to come later - perhaps for 0.8.1?

But for now, we support up to Balsam 0.5.0. I'm editing the list to reflect that.

**Comment by jlnav** [comment]
As for:

> Split or categorize regression tests by if they require additional dependencies #611

I think this is mostly satisfied by the "extra" filter label. Should I remove this entry?

**Comment by jmlarson1** [comment]
I agree

**Comment by jlnav** [comment]
We have an FBPIC multi-fidelity example in the Templater, but not the main repo. As libE-opt isn't currently public, is it appropriate to distribute an example with this release?

**Comment by jmlarson1** [comment]
I can ask the FBpic people.
