### ISSUE TITLE
Release v0.9.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#753]
Next release v0.9.0

Updates to example functions:
- [x] Moved some examples to new repository - [libe-community-examples](https://github.com/Libensemble/libe-community-examples) (VTMOP, DEAP, DeepDriveMD)  #716,  #721, #726
- [x] Updates to tasmanian examples to include asynchronous generator example #727 / #732
- [x] Added multi-task, multi-fidelity optimization regression tests using `ax` #717 / #720

New capabilities:
- [x] Support for the new `Balsam` - with multi-site capability #631, #729
- [x] Use `funcX` to place user functions on remote systems  #712 / #713
- [x] Non-blocking option for worker receives #752 
- [x] Partial support for concurrent/futures interface #719
> (cancel(), cancelled(), done(), running(), result(), exception() and context manager)
- [x] Add `match_slots` option to resource scheduler #746 
~~- [x] Add `libE_specs` option to force multiprocessing start method #778~~

API changes:
- [x] Move scheduler options to `libE_specs` #790
- [x] BalsamMPIExecutor is now LegacyBalsamMPIExecutor  #729
- [x] The exit_criteria `elapsed_wallclock_time` has been renamed `wallclock_max`  #750 (with a deprecation warning)
- [x] Improved libE field naming #760

Documentation:
- [x] Refactor examples  #737 
- [x] Refactor tutorials/toggle solutions  #736
- [x] Refactor Executor Forces tutorial for simplicity #749 
- [x] Added Perlmutter guide #728
- [x] Added Slurm guide #728
- [x] Updated history docs inc. workflow example #723 
- [x] General docs improvements #722
- [x] Running on GPU tutorial #768

**Comment by jmlarson1** [comment]
I dropped mention of dragonfly, as that was included in v0.8.0.

**Comment by jlnav** [comment]
Closed by #799 ?
