### ISSUE TITLE
Release v0.9.1

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#786]
Next Next release v0.9.1

See #815 for branch

- [x] * Many `black` changes, including string normalization. #811, #814
- [x] * Some small hotfixes. #810, #813
- [x] * A new workflows community initiative file. #817
- [x] * Added Spock and Crusher guides. #802
- [x] * User can now set ``calc_status`` to any string (for output in libE_stats). #808
