### ISSUE TITLE
Release v0.9.2 (future release)

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#820]
Next Next release v0.9.2
- [ ] Ensure `PBS` is fully supported #602 
- [ ] Configuration options for `libE_stats.txt` file #743
- [ ] Address issue with fork/spawn in multiprocessing (required for pytorch) #797
- [ ] Move comms debugging to a second debug level (as too verbose if not needed)
- [ ] Separate regression tests into problem examples and artificial tests

Possible:
- [ ] Variable resources tutorial
- [ ] Advanced/Remote forces tutorial / video
