### ISSUE TITLE
Release v.0.4.0

### ISSUE THREAD

**Issue by shuds13** [Libensemble/libensemble#94]
Next release v0.4.0

- [x] Add central_mode argument to job_controller (API addition)  #93 
- [x] Separate job controller classes into different modules (API change)
- [x] Put poll and kill as job methods (API change)
- [x] set_kill_mode is removed and replaced by a wait argument for a hard kill (API change)
- [x] Removed register module - incorporated into job_controller (API change)
- [x] Remove warning from coverage.py #92 
- [x] APOSMM has improved asynchronicity. #96 
- [x] Manager errors (instead of hangs) when alloc_f or gen_f don't return work when all workers are idle. #95

**Comment by shuds13** [comment]
Release done
